### ISSUE TITLE
require(syntax.php) is deprecated.

### ISSUE THREAD

**Issue by oleteacher** [Chris--S/dokuwiki-plugin-iframe#13]
If using PHP 8+ (and hope you are) there are errors. I am using PHP 8.1.2

The actual error from logs is:

`require(syntax.php) is deprecated. It was called from require() in /home/urxxx/xxxxxx.xxxx.net/lib/plugins/iframe/syntax.php:12 Autoloading should be used `

To address this, you can replace the __autoload() function with spl_autoload_register().

```
   // Replace this line
   require_once(DOKU_PLUGIN.'syntax.php');

   // With this line
   spl_autoload_register(function ($class) {
       require_once(DOKU_PLUGIN.'syntax.php');
   });
```

By using spl_autoload_register(), you can register multiple autoload functions in a queue and run through each of them in the order they are defined. This allows for more flexibility and avoids conflicts with other autoloaders.

This of course may break if you are still using PHP 7.+

**Comment by yaynstuff** [comment]
No comment from the author?

**Comment by Chris--S** [comment]
require() removed.  should be handled by dokuwiki.
