### ISSUE TITLE
Update date/times stamps out of synch

### ISSUE THREAD

**Issue by Miro-Collas** [Chris--S/dokuwiki-plugin-iframe#17]
Thanks for the updates! However now, Dokuwiki extension manager keeps offering the update even after updating. This apparently because the internal date is wrong:

```
Installed version:
    2016-02-02
Your last update:
    Fri, 18 Aug 2023 03:30:55 +0000
Available version:
    2023-08-17
```

I guess the one in plugin.info.txt

**Comment by Chris--S** [comment]
Should be fixed now.

**Comment by Miro-Collas** [comment]
Thank you! :-)
