### ISSUE TITLE
Handle & Render methods incompatible with latest Dokuwiki?

### ISSUE THREAD

**Issue by devuxer** [Chris--S/dokuwiki-plugin-iframe#3]
Installing this plug-in immediately causes all page requests to my wiki to return error code 500 (internal server error). Outputting the error details results in the following:

> PHP Warning:  Declaration of syntax_plugin_iframe::handle($match, $state, $pos, &$handler) should be compatible with DokuWiki_Syntax_Plugin::handle($match, $state, $pos, Doku_Handler $handler) in C:\inetpub\wwwroot\dokuwiki\lib\plugins\iframe\syntax.php on line 18

> PHP Warning:  Declaration of syntax_plugin_iframe::render($mode, &$R, $data) should be compatible with DokuWiki_Syntax_Plugin::render($format, Doku_Renderer $renderer, $data) in C:\inetpub\wwwroot\dokuwiki\lib\plugins\iframe\syntax.php on line 18

I have a feeling this may be something peculiar to my particular configuration, but I wouldn't know where to begin looking to debug the problem. I would appreciate any pointers you may have.

**Comment by Chris--S** [comment]
I suspect you may have error_level to include E_STRICT.  The correction should really come from the plugin.  I will try to remember to push an update correcting this after xmas.  For now, you can change line 24 to
```
    function handle($match, $state, $pos, Doku_Handler $handler){
```
and line 75 to
```
//    function render($mode, Doku_Renderer $R, $data) {
```

Note the changes in both cases are to remove the '&' and add the correct class hint.

**Comment by Chris--S** [comment]
Actually, what you posted are both warnings, they shouldn't cause the 500.  There might be something else.

**Comment by devuxer** [comment]
Thanks @Chris--S! Correcting the function declarations as you have above immediately solved the problem. It seems that for my particular configuration, even warnings can cause 500 errors.

**Comment by Chris--S** [comment]
fixed by https://github.com/Chris--S/dokuwiki-plugin-iframe/commit/e830f3bbe7291aaa7a8917e3252aecff2d93bd00
