### ISSUE TITLE
I propose a correction to center iframe by default

### ISSUE THREAD

**Issue by jjancel** [Chris--S/dokuwiki-plugin-iframe#9]
Hello Christopher Smith
To center the default iframe
In the syntax.php file
modify line 90
`$R->doc .= "<iframe $params>".hsc($alt).'</iframe>';`
to
`$R->doc .= "<div align='center'><iframe $params>".hsc($alt).'</iframe></div>';`
left and right iframe alignment commands still work
what is your opinion

**Comment by Chris--S** [comment]
We won’t do [deprecated attributes](https://www.tutorialspoint.com/html5/html5_deprecated_tags.htm).  Try using  the block or box plugin.
